language: node_js
node_js:
    - 4.2
before_script:
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install -g karma grunt-cli jshint'
    - 'npm install' # install npm packages
after_script:
    - 'grunt ci'
