language: node_js
node_js:
    - 6.0
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'cp config/config.example.js config/config.js'
    - 'npm install -g karma gulp-cli jshint'
    - 'npm install' # install npm packages
after_script:
    - 'gulp ci'
